files:
  # define files included in the analysis (defaults to ["{app,lib}/**/*.rb"])
  included:
    - config/**/*.rb
    - lib/**/*.rb
    - web.rb
  # define files excluded from the analysis (defaults to [])
  excluded:
    # you can use file paths
    - vendor/**/*.*
